// Code generated by goctl. DO NOT EDIT.
// Source: busis.proto

package server

import (
	"context"

	"dtm-rpc/busis"
	"dtm-rpc/internal/logic"
	"dtm-rpc/internal/svc"
)

type BusisServer struct {
	svcCtx *svc.ServiceContext
	busis.UnimplementedBusisServer
}

func NewBusisServer(svcCtx *svc.ServiceContext) *BusisServer {
	return &BusisServer{
		svcCtx: svcCtx,
	}
}

func (s *BusisServer) AddMoney(ctx context.Context, in *busis.AddReq) (*busis.Empty, error) {
	l := logic.NewAddMoneyLogic(ctx, s.svcCtx)
	return l.AddMoney(in)
}

func (s *BusisServer) DelMoney(ctx context.Context, in *busis.AddReq) (*busis.Empty, error) {
	l := logic.NewDelMoneyLogic(ctx, s.svcCtx)
	return l.DelMoney(in)
}
