// Code generated by goctl. DO NOT EDIT.

package wallets

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	walletsFieldNames          = builder.RawFieldNames(&Wallets{}, true)
	walletsRows                = strings.Join(walletsFieldNames, ",")
	walletsRowsExpectAutoSet   = strings.Join(stringx.Remove(walletsFieldNames, "id"), ",")
	walletsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(walletsFieldNames, "id"))
)

type (
	walletsModel interface {
		Insert(ctx context.Context, data *Wallets) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Wallets, error)
		Update(ctx context.Context, data *Wallets) error
		Delete(ctx context.Context, id int64) error
	}

	defaultWalletsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Wallets struct {
		Id        int64     `db:"id"`
		UserId    int64     `db:"user_id"`
		Wallet    int64     `db:"wallet"`
		CreatedAt time.Time `db:"created_at"`
		UpdatedAt time.Time `db:"updated_at"`
	}
)

func newWalletsModel(conn sqlx.SqlConn) *defaultWalletsModel {
	return &defaultWalletsModel{
		conn:  conn,
		table: `"busi"."wallets"`,
	}
}

func (m *defaultWalletsModel) withSession(session sqlx.Session) *defaultWalletsModel {
	return &defaultWalletsModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: `"busi"."wallets"`,
	}
}

func (m *defaultWalletsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultWalletsModel) FindOne(ctx context.Context, id int64) (*Wallets, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", walletsRows, m.table)
	var resp Wallets
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultWalletsModel) Insert(ctx context.Context, data *Wallets) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, walletsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Wallet, data.CreatedAt, data.UpdatedAt)
	return ret, err
}

func (m *defaultWalletsModel) Update(ctx context.Context, data *Wallets) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, walletsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Wallet, data.CreatedAt, data.UpdatedAt)
	return err
}

func (m *defaultWalletsModel) tableName() string {
	return m.table
}
